#For these messages you can also use {WORLD} to get the name of the joined or left world, WORLD2 is only supported for global messages

join-message: "&9%PLAYER% joined this world!"
leave-message: "&9%PLAYER% left this world!"
first-join-message: "&9%PLAYER% joined this world for the first time!"

join-server-message: "&9%PLAYER% joined the game!"
leave-server-message: "&9%PLAYER% left the game!"
first-server-join-message: "&9%PLAYER% joined the server for the first time!"

global-message: "&9%PLAYER% joined %WORLD%, leaving %WORLD2%!"
global-first-join-message: "&9%PLAYER% joined %WORLD% for the first time!"
global-first-join-server-message: "&9Welcome %PLAYER% to the server!"

#If you don't know what this does leave the defaults
broadcast-globally: false
error-broadcast: true
first-join-server-message: true
first-join-world-message: true

#World grouping will make that messages for player world joins (so also
# first join messages) will be broadcasted in world_nether and world_the_end.
# If world grouping is enabled, player join messages will be broadcasted to all players in world, world_nether and world_the_end,
# where 'world' is of course the name of the world.
# If world grouping is not enabled, old behaviour will be used.
world-grouping: true